// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
    production: true,
    api: 'http://localhost:8977/secureapi',
    company: 'vcp.vistingo.com',
    lstoken: 'MDzMJjldj0uCZf+DrObXFA==',
    lsrefreshtoken: 'EKHWGZB/EkSWmaO+0haEvA==',
    lsinitializationVector: 'encryptionIntVec',
    lssecretKey: 'vcompanyplatform',
    lsmenus: 'f8a6251d9b644185a084dc2f2884eae7',
    lsnotifications: 'I7jlNfkP9EOLq6IpRnclWA==',
    lsuser: '+oo1uDXXL0qFzfW/YXWAvQ==',
    lsuserId: '/oaEWl3GziBp73gy8lKR5Q==',
    lscompanyId: 'zbvlf4/ZZ+Als1cO4N1o5Q==',
    lsdomain: 'ptmkkBUowtVeAkPHsyofmw==',
    lsmemberredirect: 'tEy5wfwA/C4r7amsATFZDw==',
    lsfrominvite: 'B1KobA0mlKYzx2xkdI7bKQ==',
    lscompanies: 'Oa0F5RFPTQUJx9wj5s8WFQ==',
    lsemail:'tvjxTT/7sQeq8squTqQJ1g==',
    lslang: '2l2sOzZOsnK1QN1APhdDUA==',
    lsloginFromAs: 'FxN7owO9aK7Od8hyEJ3Gtg==',
    lsloginFromHRKlub: 'NtZkLtjxfB+7N8bShUMpdw==',
    lsfeatures: '5jGcWCOAaHCTIav98+Y6GQ==',
    lsversionHash: 'QjVxbqGVX6FLe6zeOXl2aw==',
    lsavatar: '2xEH3hWnbGhjqJ7Gmh48wA==',
    lscourseVideoId: 'wlqz7vtvMXvyJ77RzhniyA==',
    lsuserRole: '+S45EICXvlbkKfSAGLbk0A==',
    lskeyword: 'z+aXsxQZ3sUfho8Vq2CxRw==',
    lsresults: 'nb4Co1rtlHhExGioYP4Z3Q==',
    lstopage: 'QqlJaV7ypHHGytpasAYROQ==',
    lssettings: 'VyLoDsl/2jSkQOYh/RSViw==',
    lsnotificationmodal: '9uFLZmdJ79bBkR73yVQqSqfTk8oEsiJdObILauUAKqQ=',
    lsevent: 'bYMnYqe1w8K8+nMmH8OqbQ==',
    lsmemberType: 'gavZpzrbmU9n02SBVtSyVA==',
    lsguid: 'o0Ujddz0E1Pl41sNXm/HxA==',
    lsCourseVideoId: 'wlqz7vtvMXvyJ77RzhniyA==',
    lscoursetitle: 'vJV0Llrh5gImg02EkElxuw==',
    lscourseunit: 'WRvVk13lOWb5DwnZus/kwA==',
    lsselectedGroupFilter: 'tC7RNEuT7mcVhCTlrhbgJMMuCnDXzxyKX8K+ak0m6Cs=',
    lsselectedGroupFilterId: 'tC7RNEuT7mcVhCTlrhbgJF18z7wa+gOslkp0L0FbFP0=',
    lsgroupId: 'zBXa0dy7W+aZ++QAvset4g==',
    lsclubId: '88l4Z3VpcTCqTR9poLVCzg==',
    lsgroup: 'mHUCn8IA2s8n2WMoVpfSzg==',
    lsfromGroupDetails: 'kxpvWmfpUxD3xKX00Ls/zxtSf1ak4V2m7I+as/KJv8Q=',
    lszoommember: 'J5qSbR4lTfqELIwlaaqlKA==',
    lszoomuser: '56z5KO341yEfBMye5kPGSQ==',
    lszoomredirect: 'H1bHF6DFmFlCHtvzzi8GDQ==',
    lscompanyurl: 'XWRhgF7etYX8nbRS729LyA==',
    lsplanId: '7/vT/vcP8hQsnQnwG+M/2g==',
    lsemailinvitequestions: '9K4amVlKigm3t59+cJEfctkD7gITpTQes0L27QWsZJE=',
    lsinvitedby: 'tkPeB0HxNOjsS2VIciqNNA==',
    lseventinvite: 'y8UbiGd8PF+00EpIap9qmg==',
    lsinvitedbyguid: 'TDt2bDTeivC4WZ7D1d/DdA==',
    lsmedicalplan: '3cwymwcqbQVJMX+O52hePg==',
    lslanguage: '4TKRnWUEL2SVFDADkxnPIA==',
    lsvcpadmin: 'mb0m3SNyT3tcz+vr3C8SKw==',
    lsselectedMemberType: 'M/GzWYcqXiWhFGxW1khMIVZG+dGJvB33PCoHRDo3FIE=',
    lsplanFrequency: '6ybgnqju0QAUOYMXaec6Uw==',
    lsselectedStartupId: 'dkNaJ4H+6b6jBkprQyMDlRcjP/LtaocPIKTsIKDOsBA=',
    lsselectedStartupName: 'Ma+S6HbjETnDt98s2OAomLyTnN0cFHNhbSqob1ePDsc=',
    lsselectedStartup: 'ipn5JKZIG3uFdIEwEr3AkQ==',
    lsstartuplogofile: '3QedIht8z6UJlhkzLkl4Aw==',
    lsretlabMemberType: 'LeC9AQbei5UQW41FztVe4VVmhNbV4yk1KKmPXsfIREE=',
    lstoastdismissed: 'xpD4rFXWXH0CIUd+BttDFA==',
    lstoastopened: 'Tzfo108nKrwFrgTLGyIBoQ==',
    lscurrentUser: '9NyA+8LfvCQYqRNfMvBMCA==',
    lsreport: 'UjwYsku9FFqhu/hsCtnS4g==',
    lstutortypes: 'VsPZU9fGTkeAnzcI96Gbug==',
    lsusergeocountry: "9tUVhOGJtEa0brNJCgI7tA==",
    lsusergeocity: "dYvVSQsQU0yuMBCmjuE3Xg==",
    lsusergeoipaddress: "y8Y+yUkz7E6QhkVODnJYWw==",
    lsguestaccesstoken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZW1haWwiOiIiLCJyb2xlIjoiTSIsImd1aWQiOiIiLCJpYXQiOjE3MDgyNDc4NzB9.PWfu6_YIvd56bK-YsX9qAvW9cwdYzeW7ZYWhLWlOwqU"
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
